name: Build
on: [push]
jobs:
  Explore-GitHub-Actions:
    name: Convert to HTML
    runs-on: ubuntu-latest
    steps:
      - uses: ZacJW/markdown-html-action@1.2.0
        with:
          input_files: '[["docs/fsharp-cheatsheet.md"]]'
          output_files: '["docs/fsharp-cheatsheet.html"]'
