name: Build
on: [push]
jobs:
  build:
    name: Convert to HTML
    runs-on: ubuntu-latest
    steps:
      - uses: ZacJW/markdown-html-action@1.1.0
        with:
          input_files: '[["*.md"]]'
          output_files: '["docs/fsharp-cheatsheet.html"]'
          packages: 'pymdown-extensions'
